# PowerShell build script for Windows
# Located at .github/scripts/windows-build.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Write-Host "Starting Windows build..."

python -m pip install --upgrade pip
pip install -r anonymikeconnect/requirements.txt
pip install pyinstaller

# Clean previous builds
if (Test-Path ./dist) { Remove-Item -Recurse -Force ./dist }
if (Test-Path ./build) { Remove-Item -Recurse -Force ./build }
if (Test-Path ./ANONYMIKECONNECTV1.0.spec) { Remove-Item -Force ./ANONYMIKECONNECTV1.0.spec }

# Build the EXE. Adjust the entrypoint if you prefer main.py
$entry = "anonymikeconnect/run_anonymikeconnect.py"
Write-Host "Using entrypoint: $entry"
pyinstaller --onefile --name ANONYMIKECONNECTV1.0 $entry

$exePath = Join-Path -Path (Resolve-Path ./dist) -ChildPath "ANONYMIKECONNECTV1.0.exe"
if (-not (Test-Path $exePath)) {
    Write-Error "Build failed: $exePath not found"
    exit 1
}

# Compute SHA256 and size
$hash = Get-FileHash -Algorithm SHA256 $exePath
$sha256 = $hash.Hash
$size = (Get-Item $exePath).Length

Write-Host "Built: $exePath"
Write-Host "SHA256: $sha256"
Write-Host "Size: $size"

# Simple smoke test: --help or --version if supported
try {
    & $exePath --version 2>$null | Out-Null
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0 -and $exitCode -ne $null) {
        Write-Warning "Exe returned non-zero exit code ($exitCode) for --version. Continuing but consider adding more robust tests."
    }
} catch {
    Write-Warning "Smoke test failed to run; the exe may still be valid depending on app behavior. Error: $_"
}

# Write release metadata for the workflow to consume
$releaseMeta = [PSCustomObject]@{
    version = "ANONYMIKECONNECTV1.0"
    file = "ANONYMIKECONNECTV1.0.exe"
    path = $exePath
    sha256 = $sha256
    size = $size
    notes = "Windows build generated by CI."
}
$releaseMeta | ConvertTo-Json | Out-File -Encoding UTF8 release.json

Write-Host "Wrote release.json"
Write-Host (Get-Content release.json -Raw)
